# Generated by Django 4.2.1 on 2023-05-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairytale', '0008_alter_story_id_alter_storyelement_element_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storyelement',
            name='element_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
