# Generated by Django 4.2.1 on 2023-05-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairytale', '0010_rename_story_name_storyelement_story_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyelement',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
