# Generated by Django 3.1.3 on 2023-04-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageAI', '0007_auto_20230414_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
