# Generated by Django 4.2.1 on 2023-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageAI', '0008_inputtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtext',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
