# Generated by Django 3.1.3 on 2023-04-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageAI', '0003_auto_20230414_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
