# Generated by Django 3.1.3 on 2023-04-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageAI', '0004_auto_20230414_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'uploaded_images',
            },
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='text',
            field=models.TextField(),
        ),
    ]
