# Generated by Django 3.1.3 on 2023-04-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageAI', '0006_delete_uploadedimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
