# Generated by Django 4.2.1 on 2023-05-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairytale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyelement',
            old_name='user',
            new_name='author',
        ),
    ]
