# Generated by Django 4.2.1 on 2023-05-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairytale', '0002_rename_user_storyelement_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyelement',
            name='author',
        ),
        migrations.AddField(
            model_name='storyelement',
            name='text',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='storyelement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storyelement',
            name='image',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
