# Generated by Django 4.2.1 on 2023-05-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairytale', '0003_remove_storyelement_author_storyelement_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyelement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storyelement',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='fairytale.story'),
        ),
    ]
