# Generated by Django 4.2.1 on 2023-05-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairytale', '0004_alter_storyelement_id_alter_storyelement_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyelement',
            name='story',
            field=models.ForeignKey(db_column='story_id', on_delete=django.db.models.deletion.CASCADE, related_name='story', to='fairytale.story'),
        ),
        migrations.RenameField(
            model_name='storyelement',
            old_name='story',
            new_name='story_id',
        ),
    ]
