# Generated by Django 4.2.1 on 2023-05-17 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fairytale', '0005_alter_storyelement_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storyelement',
            name='story_id',
            field=models.ForeignKey(db_column='story_id', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='fairytale.story'),
        ),
    ]
