# Generated by Django 4.2.1 on 2023-05-17 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fairytale', '0007_rename_id_storyelement_element_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='storyelement',
            name='element_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
