# Generated by Django 4.2.1 on 2023-06-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairytale", "0011_alter_storyelement_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="title_num",
            field=models.CharField(default="0", max_length=200),
        ),
    ]
