# Generated by Django 3.1.3 on 2023-04-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageAI', '0005_auto_20230414_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImages',
        ),
    ]
